config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, skip: :all
  devise_scope :admin_user do
    get 'admin/login' => 'devise/sessions#new', as: :new_admin_user_session
    post 'login' => 'devise/sessions#create', as: :admin_user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_user_session
  end
  root "questionnaires#new"
  resources :questionnaires, only: %i[new show create destroy]
  resource :admin_users, only: %i[show] do
    get "api" => "admin_users#index"
    get "table" => "admin_users#table"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  enum school_year: { 学部1年: 1, 学部2年: 2, 学部3年: 3, 学部4年: 4, 修士1年: 5, 修士2年: 6, その他: 99 }
  enum conscious_working: { はい: 0, いいえ: 1 }, _suffix: true
  enum from_now: { はい: 0, いいえ: 1 }, _suffix: true
  enum anxiety: { はい: 0, いいえ: 1 }, _suffix: true
  enum most_select_reason: {
    給料:1, 福利厚生:2, 業務内容:3, 今までの経験が活かせるもの:4, 通勤時間:5, 職場の雰囲気:6,
    自分のやりたいことに取り組めるか:7, 企業ブランド:8, 特になし:99
  }
  validates :conscious_working, presence: true
  validates :anxiety, presence: true
  validates :school_year, presence: true
  validates :university_name, length: { maximum: 20 }

  validate :from_now_validation
  # 問③ではいをつけた人(=>問８)も問６が答えられるようになっている
  # =>問５を問３ではいと答えた人に答えられなくするvalidattionを設定
  def from_now_validation
    if from_now.present? && conscious_working == "はい"
      errors.add(:from_now, 'は問３が"いいえ"の人のみ回答してください')
    end
  end
  # Todo: 問８、10のvalidation設定
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :authenticate_admin_user!
  def show; end

  def index
    render json: Questionnaire.all
  end

  def table
    @questionnaires = Questionnaire.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
    admin_users_path
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  def new
    @questionnaire = Questionnaire.new
  end

  def create
    @questionnaire = Questionnaire.new(params_questionnaire)
    if @questionnaire.save
      redirect_to @questionnaire
      flash[:notice] = "アンケートを回答しました！ご協力ありがとうございました。"
    else
      render 'new'
    end
  end

  def show; end

  def destroy
    Questionnaire.find(params[:id]).destroy
    flash[:notice] = "削除しました"
    redirect_to table_admin_users_url
  end


  private
  def params_questionnaire
    params.require(:questionnaire).permit(*key_names)
  end

  def key_names
    [
      :school_year,
      :university_name,
      :conscious_working,
      :search_site,
      :analysis_myself,
      :practice_interview,
      :practice_es,
      :join_internship,
      :attend_job_fair,
      :interview_company,
      :selection_by_company,
      :other,
      :from_now,
      :search_site_no,
      :analysis_myself_no,
      :practice_interview_no,
      :practice_es_no,
      :join_internship_no,
      :attend_job_fair_no,
      :other_no,
      :when_to_start,
      :nothing_schedule,
      :anxiety,
      :how_to_do,
      :start,
      :prepare,
      :job_offer,
      :nothing_to_do,
      :decision,
      :talk_interview,
      :write_es,
      :just_because,
      :less_info,
      :continue_to_work,
      :unknown_myself,
      :other_anxiety,
      :description_internship,
      :consultation,
      :nothing_anxiety,
      :all_right,
      :join_internship_reason,
      :other_no_anxiety,
      :most_select_reason,
    ]
  end


end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def conscious_working_calculation(count)
    q_count = Questionnaire.where(conscious_working: "はい").count
    return_result(count, q_count)
  end

  def q_all_caliculation(count)
    q_count = Questionnaire.count
    return_result(count, q_count)
  end

  def q_5_caliculation(count)
    q_count = Questionnaire.where(conscious_working: "いいえ").count
    return_result(count, q_count)
  end

  def q_6_caliculation(count)
    q_count = Questionnaire.where(from_now: "はい").count
    return_result(count, q_count)
  end

  def q_9_caliculation(count)
    q_count = Questionnaire.where(anxiety: "はい").count
    return_result(count, q_count)
  end

  # Todo: ここだけなぜかto_f(1/0.0)はエラーが発生
  # =>10をlastに変えたら解決原因は不明
  def q_last_caliculation(count)
    q_count = Questionnaire.where(anxiety: "いいえ").count
    return_result(count, q_count)
  end

  def return_result(count, q_count)
    if q_count == 0
      "-"
    else
      (count / q_count.to_f * 100).round(0)
    end
    rescue ZeroDivisionError
      0
  end

end

app/views/admin_users/show.html.erb
<h1>結果表示</h1>
<h3>回答数: <%= Questionnaire.count %></h3><br>
<%= link_to "詳細表示", table_admin_users_path, class: "btn btn-primary", target: "_blank" %>
<br><br>
<h5>問3 就活を意識して何か取り組んでいる: <%= q_all_caliculation(Questionnaire.where(conscious_working: "はい").count) %>%</h5>

<h5>問4 はいの場合何をしているか</h5>
<!-- Todo: validation設定.今のままだと全体のカラム/はいのカラムなので100%を超える可能性がある -->
<!-- はい＆＆conscious_workingがはいの人をconscious_workingがはいの人で割ることで解決! -->
<ul>
  <li>企業調べをしている:<%= conscious_working_calculation(Questionnaire.where(search_site: 1, conscious_working: 0).count) %>%</li>
  <li>自己分析をしている:<%= conscious_working_calculation(Questionnaire.where(analysis_myself: 1, conscious_working: 0).count) %>%</li>
  <li>面接対策をしている:<%= conscious_working_calculation(Questionnaire.where(practice_interview: 1, conscious_working: 0).count) %>%</li>
  <li>ES対策をしている:<%= conscious_working_calculation(Questionnaire.where(practice_es: 1, conscious_working: 0).count) %>%</li>
  <li>インターンに参加している:<%= conscious_working_calculation(Questionnaire.where(join_internship: 1, conscious_working: 0).count) %>%</li>
  <li>説明会に参加している:<%= conscious_working_calculation(Questionnaire.where(attend_job_fair: 1, conscious_working: 0).count) %>%</li>
  <li>企業と面談している:<%= conscious_working_calculation(Questionnaire.where(interview_company: 1, conscious_working: 0).count) %>%</li>
  <li>選考面接を既に受けた:<%= conscious_working_calculation(Questionnaire.where(selection_by_company: 1, conscious_working: 0).count) %>%</li>
  <li>その他:<%= conscious_working_calculation(Questionnaire.where(other: 1, conscious_working: 0).count) %>%</li>
</ul>

<h5>問5 これから就活に取り組もうとしている: <%= q_5_caliculation(Questionnaire.where(from_now: "はい").count) %>%</h5>

<h5>問6 はいの場合何をしているか</h5>
<ul>
  <li>就活サイト等で企業調べをしている:<%= q_6_caliculation(Questionnaire.where(search_site_no: 1, from_now: 0).count) %>%</li>
  <li>自己分析をしている:<%= q_6_caliculation(Questionnaire.where(analysis_myself_no: 1, from_now: 0).count) %>%</li>
  <li>面接対策をしている:<%= q_6_caliculation(Questionnaire.where(practice_interview_no: 1, from_now: 0).count) %>%</li>
  <li>ES対策をしている:<%= q_6_caliculation(Questionnaire.where(practice_es_no: 1, from_now: 0).count) %>%</li>
  <li>インターンに参加している:<%= q_6_caliculation(Questionnaire.where(join_internship_no: 1, from_now: 0).count) %>%</li>
  <li>説明会に参加している:<%= q_6_caliculation(Questionnaire.where(attend_job_fair_no: 1, from_now: 0).count) %>%</li>
  <li>その他:<%= q_6_caliculation(Questionnaire.where(other_no: 1, from_now: 0).count) %>%</li>
</ul>

<h5>問8 就活に対して不安があるか: <%= q_all_caliculation(Questionnaire.where(anxiety: "はい").count) %>%</h5>

<h5>問9 はいの場合何が不安か</h5>
<ul>
  <li>就活のやり方がわからない:<%= q_9_caliculation(Questionnaire.where(how_to_do: 1, anxiety: 0).count) %>%</li>
  <li>開始時期がわからない:<%= q_9_caliculation(Questionnaire.where(start: 1, anxiety: 0).count) %>%</li>
  <li>事前準備がわからない:<%= q_9_caliculation(Questionnaire.where(prepare: 1, anxiety: 0).count) %>%</li>
  <li>内定をもらえるのか不安:<%= q_9_caliculation(Questionnaire.where(job_offer: 1, anxiety: 0).count) %>%</li>
  <li>自分のやりたいことがない:<%= q_9_caliculation(Questionnaire.where(nothing_to_do: 1, anxiety: 0).count) %>%</li>
  <li>就職先をなにで決めるべきかわからない:<%= q_9_caliculation(Questionnaire.where(decision:1, anxiety: 0).count) %>%</li>
  <li>面接で何を話せばいいか:<%= q_9_caliculation(Questionnaire.where(talk_interview: 1, anxiety: 0).count) %>%</li>
  <li>ESの書き方を知らない:<%= q_9_caliculation(Questionnaire.where(write_es: 1, anxiety: 0).count) %>%</li>
  <li>漠然と不安:<%= q_9_caliculation(Questionnaire.where(just_because: 1, anxiety: 0).count) %>%</li>
  <li>情報が少ない:<%= q_9_caliculation(Questionnaire.where(less_info: 1, anxiety: 0).count) %>%</li>
  <li>内定先が決まってもそこで働き続けられるかわからない:<%= q_9_caliculation(Questionnaire.where(continue_to_work: 1, anxiety: 0).count) %>%</li>
  <li>自己分析ができない:<%= q_9_caliculation(Questionnaire.where(unknown_myself: 1, anxiety: 0).count) %>%</li>
  <li>その他:<%= q_9_caliculation(Questionnaire.where(other_anxiety: 1, anxiety: 0).count) %>%</li>
</ul>

<h5>問10 いいえの場合なぜ不安がないのか</h5>
<ul>
  <li>もともと不安がない:<%= q_last_caliculation(Questionnaire.where(nothing_anxiety: 1, anxiety: 1).count) %>%</li>
  <li>周りの人の状況を聞く限り不安に思わない:<%= q_last_caliculation(Questionnaire.where(all_right: 1, anxiety: 1).count) %>%</li>
  <li>インターンなどに参加した:<%= q_last_caliculation(Questionnaire.where(join_internship_reason: 1, anxiety: 1).count) %>%</li>
  <li>不安がない理由その他:<%= q_last_caliculation(Questionnaire.where(other_no_anxiety: 1, anxiety: 1).count) %>%</li>
</ul>

<br>
<%#= link_to "API表示", api_admin_users_path, class: "btn btn-primary" %><br><br>
<%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, class: "btn btn-danger" %>
<br><br><br>

app/views/admin_users/table.html.erb
<table>
  <thead>
    <tr>
      <th>番号</th>
      <th>学年</th>
      <th>大学名</th>
      <th>問7 いつごろから?</th>
      <th>問9 インターンの経験(あれば)</th>
      <th>問9 相談相手(あれば)</th>
      <th>問11 最も重要視する点</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @questionnaires.each do |q| %>
      <tr>
        <td><%= q.id %></td>
        <td><%= q.school_year %></td>
        <td><%= q.university_name %></td>
        <td>
          <% if q.conscious_working == "はい" %>
            -
          <% elsif q.nothing_schedule.present? && q.from_now == "いいえ" %>
            就活する予定はない
          <% else %>
            <%= q.when_to_start.to_s(:date) %>
          <% end %>
        </td>
        <td><%= q.description_internship.present? && q.anxiety == "はい" ? q.description_internship : "-" %></td>
        <td><%= q.consultation.present? && q.anxiety == "はい" ? q.consultation : "-" %></td>
        <td><%= q.most_select_reason %></td>
        <td><%= link_to "削除", q, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>就活アンケート</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- 端末のサイズに応じて画面を描写 -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <div class="container main-page">
      <%# Todo: InvalidAuthenticityToken解決 %>
      <br>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questionnaires/new.html.erb
<h1>アンケート</h1>
<br>
<p></p>
<%= form_for @questionnaire do |f| %>
<%= render "shared/error_messages", object: @questionnaire %>
  <p>問１ あなたの学年を教えてください<span class="red">*</span></p>
  <%= f.select :school_year, Questionnaire.school_years.keys.to_a, {} %><br><hr>

  <p>問２ あなたの大学名を教えてください</p>
  <%= f.text_field :university_name, placeholder: "△△大学", class: "form-control" %>
  <hr>

  <p>問3 就活を意識して何か取り組んでいますか？</p>
  <%# Todo: ラジオボタン二度押しで選択解除 %>
  <!-- Todo:チェックをつけてIDパスを実装 -->
  <!-- <a href="#question_4" class="question_4c"><%#= f.radio_button :conscious_working, "はい" %></a> -->
  <%= f.radio_button :conscious_working, "はい", class: "question_4c" %>
  <%= f.label :conscious_working, value: "はい" %>
  <%= f.radio_button :conscious_working, "いいえ", class: "question_5c" %>
  <%= f.label :conscious_working, value: "いいえ" %>
  <br><br>
  <p>はいの人⏩<a class="question_4c">次へ</a></p>
  <p>いいえの人⏩<a class="question_6c">問6へ</a></p>
  <br>
  <hr>

  <p id="question_4">問4 <span class="red">問3が"はい"の人のみ</span></p>
  <p>具体的にどのようなことをしていますか？(複数選択可)</p>
  <%= f.check_box :search_site, {}, "true", "false" %>
  <%= f.label :search_site, "就活サイト等で企業調べをしている" %><br>

  <%= f.check_box :analysis_myself, {}, "true", "false" %>
  <%= f.label :analysis_myself, "自己分析している" %><br>

  <%= f.check_box :practice_interview, {}, "true", "false" %>
  <%= f.label :practice_interview, "面接対策をしている" %><br>

  <%= f.check_box :practice_es, {}, "true", "false" %>
  <%= f.label :practice_es, "ES対策をしている" %><br>

  <%= f.check_box :join_internship, {}, "true", "false" %>
  <%= f.label :join_internship, "インターンに参加している" %><br>

  <%= f.check_box :attend_job_fair, {}, "true", "false" %>
  <%= f.label :attend_job_fair, "説明会に参加している" %><br>

  <%= f.check_box :interview_company, {}, "true", "false" %>
  <%= f.label :interview_company, "企業と面談している" %><br>

  <%= f.check_box :selection_by_company, {}, "true", "false" %>
  <%= f.label :selection_by_company, "選考面接を既に受けた" %><br>

  <%= f.check_box :other, {}, "true", "false" %>
  <%= f.label :other, "その他" %><br>
  <br><br>
  <p><a class="question_8c">問8へ</a></p>
  <hr>

  <p id="question_5">問5 <span class="red">問3が"いいえ"の人のみ</span></p>
  <p>これから就活に取り組もうとしていますか？<span class="red">*</span></p>
  <%= f.radio_button :from_now, "はい", class: "question_6c" %>
  <%= f.label :from_now, value: "はい" %>
  <%= f.radio_button :from_now, "いいえ", class: "question_7c" %>
  <%= f.label :from_now, value: "いいえ" %>
  <br><br>
  <!-- Todo:リンク実装 -->
  <p>はいの人⏩<a class="question_6c">次へ</a></p>
  <p>いいえの人⏩<a class="question_7c">問7へ</a></p>
  <br>
  <hr>

  <p id="question_6">問6 <span class="red">問5が"はい"の人のみ</span></p>
  <p>どのようなことに取り組もうとしていますか？(複数選択可)</p>
  <%= f.check_box :search_site_no, {}, "true", "false" %>
  <%= f.label :search_site_no, "就活サイト等で企業調べをしている" %><br>

  <%= f.check_box :analysis_myself_no, {}, "true", "false" %>
  <%= f.label :analysis_myself_no, "自己分析をしている" %><br>

  <%= f.check_box :practice_interview_no, {}, "true", "false" %>
  <%= f.label :practice_interview_no, "面接対策をしている" %><br>

  <%= f.check_box :practice_es_no, {}, "true", "false" %>
  <%= f.label :practice_es_no, "ES対策をしている" %><br>

  <%= f.check_box :join_internship_no, {}, "true", "false" %>
  <%= f.label :join_internship_no, "インターンに参加している" %><br>

  <%= f.check_box :attend_job_fair_no, {}, "true", "false" %>
  <%= f.label :attend_job_fair_no, "説明会に参加している" %><br>

  <%= f.check_box :other_no, {}, "true", "false" %>
  <%= f.label :other_no, "その他" %><br>
  <br><br>
  <!-- Todo:リンク実装 -->
  <p><a class="question_8c">問8へ</a></p>
  <hr>


  <p id="question_7">問7 <span class="red">問5が"いいえ"の人のみ</span></p>
  <p>いつ頃から就活に取り組むつもりですか？</p>
  <%== sprintf(
  f.date_select(:when_to_start, use_month_numbers: true, discard_day: true,
  start_year: Time.now.year, end_year: Time.now.year + 1, default: Time.now.to_date), '年','月') + '月ごろ' %><br><br>

  <%= f.check_box :nothing_schedule, {}, "true", "false" %>
  <%= f.label :nothing_schedule, "就活する予定はない" %>
  <br><br>
  <!-- Todo:リンク実装 -->
  <p><a class="question_8c">次へ</a></p>
  <hr>


  <p id="question_8">問８ 就活に対して不安がありますか？<span class="red">*</span></p>
  <%= f.radio_button :anxiety, "はい", class: "question_9c" %>
  <%= f.label :anxiety, value: "はい" %>
  <%= f.radio_button :anxiety, "いいえ", class: "question_10c" %>
  <%= f.label :anxiety, value: "いいえ" %>
  <br>
  <hr>


  <p id="question_9">問９ <span class="red">問8が"はい"の人だけお答えください</span></p>
  <p>どのような不安がありますか？(複数選択可)</p>

  <%= f.check_box :how_to_do, {}, "true", "false" %>
  <%= f.label :how_to_do, "就活のやり方がわからない" %><br>

  <%= f.check_box :start, {}, "true", "false" %>
  <%= f.label :start, "開始時期がわからない" %><br>

  <%= f.check_box :prepare, {}, "true", "false" %>
  <%= f.label :prepare, "事前準備がわからない" %><br>

  <%= f.check_box :job_offer, {}, "true", "false" %>
  <%= f.label :job_offer, "内定をもらえるのか不安" %><br>

  <%= f.check_box :nothing_to_do, {}, "true", "false" %>
  <%= f.label :nothing_to_do, "自分のやりたいことがない" %><br>

  <%= f.check_box :decision, {}, "true", "false" %>
  <%= f.label :decision, "就職先を何で決めるべきかわからない" %><br>

  <%= f.check_box :talk_interview, {}, "true", "false" %>
  <%= f.label :talk_interview, "面接で何を話せばいいかわからない" %><br>

  <%= f.check_box :write_es, {}, "true", "false" %>
  <%= f.label :write_es, "ESの書き方がわからない" %><br>

  <%= f.check_box :just_because, {}, "true", "false" %>
  <%= f.label :just_because, "漠然と不安だ" %><br>

  <%= f.check_box :less_info, {}, "true", "false" %>
  <%= f.label :less_info, "情報が少ない" %><br>

  <%= f.check_box :continue_to_work, {}, "true", "false" %>
  <%= f.label :continue_to_work, "内定先が決まってもそこで働き続けられるかわからない" %><br>

  <%= f.check_box :unknown_myself, {}, "true", "false" %>
  <%= f.label :unknown_myself, "自己分析ができない" %><br>

  <br>
  <%# Todo:その他jQuery実装 %>
  <%= f.check_box :other_anxiety, {}, "true", "false" %>
  <%= f.label :other_anxiety, "その他" %>
    <p>その他を選んだ人にお聞きします</p>
    <%= f.label :description_internship, "インターンに参加した具体的なエピソード" %>
    <%= f.text_area :description_internship, placeholder: "私は○○で△△な経験を積みました", class: "form-control" %>
    <br>
    <%= f.label :consultation, "相談相手" %>
    <%= f.text_field :consultation, placeholder: "友人、教授、親等", class: "form-control" %>
  <br><br>
  <!-- Todo:リンク実装 -->
  <p><a class="question_11c">問11へ</a></p>
  <hr>

  <p id="question_10">問10 <span class="red">問8が"いいえ"の人のみ</span></p>
  <p>なぜ不安がないのですか？(複数選択可)</p>

  <%= f.check_box :nothing_anxiety, {}, "true", "false" %>
  <%= f.label :nothing_anxiety, "もともと不安がない" %><br>

  <%= f.check_box :all_right, {}, "true", "false" %>
  <%= f.label :all_right, "周りの状況を聞く限り不安に思わない" %><br>

  <%= f.check_box :join_internship_reason, {}, "true", "false" %>
  <%= f.label :join_internship_reason, "インターンなどに参加したから" %><br>

  <%= f.check_box :other_no_anxiety, {}, "true", "false" %>
  <%= f.label :other_no_anxiety, "その他" %>
  <br><hr>


  <p id="question_11">問11 就活において最も重要視するのはどれですか？</p>
  <%= f.select :most_select_reason, Questionnaire.most_select_reasons.keys.to_a, {} %>

<br><hr>
<%= f.submit "送信する", class: "btn btn-primary" %>
<% end %>
<br><br>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count %>個エラーがあります
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="red"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>